services:
  database:
    image: postgres:13
    container_name: database2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  profile-service:
    build: .
    ports:
      - "3000:3000"
    container_name: profile-service
    restart: always
volumes:
  postgres-data:  # Itt definiáljuk a postgres-data volumenet